### PR TITLE
Updated learn docs

### PR DESCRIPTION
**Pull request by evgenyponomarev**
Rolled out new content for the "Learn" section

### CODE REVIEW

**Comment by shamsartem** [comment]
I would suggest using sequential headings (# then ## and only then ### without skipping). That's not a stylistic decision but a logical one, this heading levels are also used for table of contents creation among other things. I can commit that change

**Comment by evgenyponomarev** [comment]
@shamsartem i didn't like how h2 look in some places and chose what is visually better based on content amount. It doesn't matter so much really.

**Comment by shamsartem** [comment]
> @shamsartem i didn't like how h2 look in some places and chose what is visually better based on content amount. It doesn't matter so much really.

I get it. If you don't mind - I would change it. If stylistic preference is very important for you - of course we can leave it as it is, it's not a critical issue

**Comment by evgenyponomarev** [comment]
> > @shamsartem i didn't like how h2 look in some places and chose what is visually better based on content amount. It doesn't matter so much really.
> 
> I get it. If you don't mind - I would change it. If stylistic preference is very important for you - of course we can leave it as it is, it's not a critical issue

Ok, do it

**Review by shamsartem — APPROVED** [review]

**Pull request merged**
