### PR TITLE
migrate docs

### PR DESCRIPTION
**Pull request by shamsartem**

### CODE REVIEW

**Review by boneyard93501 — COMMENTED** [review]
looks great. couple things:
* Docs column in the footer seems superfluous
* not sure about the entry slide. can't we just go straight to the default doc ?

**Comment by boneyard93501** [comment]
all the `Edit this page` links at bottom of pages are dead and should be removed anyway.

**Comment by shamsartem** [comment]
> * Docs column in the footer seems superfluous

When on mobile and you scroll to the bottom - user can decide to use those links - otherwise sidebar needs to be opened. We can put something specific there or just remove that column, of course. I don't see much harm in it really, I would keep it
I can basically put whatever you decide there, e.g. YouTube link is missing in the Community column, etc.

> * not sure about the entry slide. can't we just go straight to the default doc ?

In the huge post in slack, I talked a little bit about that. Basically, we can add something cool there if we want to, or we can set up a server-side redirect to the introduction page for the time being, but that can be done only when we decide to publish

> all the Edit this page links at bottom of pages are dead and should be removed anyway.

They are dead because code is not merged yet. They should work after that. I would disagree that they should be removed, the easy of editing would encourage us to keep docs up in shape. I think it's pretty convenient that anyone can go straight ahead and do small doc improvements. Maybe there are some reasons I don't know for you to think they should be removed, please share if you think it's important

> since readers can't actually edit main, or at least i hope they can't, any link should be to where the PR instructions are.

**Review by alari — APPROVED** [review]

**Comment by mikevoronov** [comment]
`Edit this page` on every page points to nowhere

**Review by mikevoronov — APPROVED** [review]
Great job!

**Pull request merged**
